#!/usr/bin/env python3
"""
Auto-register all AGMap UDFs in Flink SQL

This script scans agmap_registry.py for all UDTF definitions and generates
SQL CREATE FUNCTION statements to register them automatically.

Usage:
    python scripts/auto_register_udfs.py

Output:
    Prints SQL statements to stdout that can be executed in Flink SQL
"""

import re
import sys
from pathlib import Path


def extract_udtf_names(registry_file: Path) -> list[tuple[str, str]]:
    """
    Extract UDTF function names and their return types from agmap_registry.py

    Returns:
        List of tuples: (function_name, return_types_description)
    """
    if not registry_file.exists():
        print(f"Error: {registry_file} not found", file=sys.stderr)
        return []

    content = registry_file.read_text()

    # Pattern to match @udtf decorator and function definition
    # Example: @udtf(result_types=[DataTypes.STRING(), DataTypes.DOUBLE()])
    #          def agmap_sentiment(input_data):
    pattern = r"@udtf\(result_types=\[(.*?)\]\)\s*\ndef\s+(\w+)\s*\("

    matches = re.findall(pattern, content, re.DOTALL)

    functions = []
    for return_types, func_name in matches:
        # Clean up the return types string
        return_types_clean = return_types.replace("\n", " ").strip()
        functions.append((func_name, return_types_clean))

    return functions


def generate_registration_sql(functions: list[tuple[str, str]]) -> str:
    """Generate SQL CREATE FUNCTION statements for all UDTFs"""

    sql_statements = []

    # Add header comment
    sql_statements.append("-- Auto-generated UDF Registration")
    sql_statements.append("-- Generated by auto_register_udfs.py")
    sql_statements.append("--")
    sql_statements.append(f"-- Total functions: {len(functions)}")
    sql_statements.append("")

    # Register dynamic mode function
    sql_statements.append("-- Dynamic Mode UDF (single field extraction)")
    sql_statements.append("CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap")
    sql_statements.append("AS 'ag_operators.agmap' LANGUAGE PYTHON;")
    sql_statements.append("")

    # Register AGReduce
    sql_statements.append("-- AGReduce UDF (aggregation)")
    sql_statements.append("CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agreduce")
    sql_statements.append("AS 'agreduce.agreduce' LANGUAGE PYTHON;")
    sql_statements.append("")

    # Register AGSearch
    sql_statements.append("-- AGSearch UDF (vector search)")
    sql_statements.append("CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agsearch")
    sql_statements.append("AS 'agsearch.agsearch' LANGUAGE PYTHON;")
    sql_statements.append("")

    # Register explode_search_results
    sql_statements.append("-- Explode Search Results UDTF")
    sql_statements.append(
        "CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS explode_search_results"
    )
    sql_statements.append("AS 'agsearch.explode_search_results' LANGUAGE PYTHON;")
    sql_statements.append("")

    # Register AGPersist Search functions
    sql_statements.append("-- AGPersist Search UDFs (persistent vector indexes)")
    sql_statements.append(
        "CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS build_search_index"
    )
    sql_statements.append("AS 'agpersist_search.build_search_index' LANGUAGE PYTHON;")
    sql_statements.append("")
    sql_statements.append(
        "CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS search_index_json"
    )
    sql_statements.append("AS 'agpersist_search.search_index_json' LANGUAGE PYTHON;")
    sql_statements.append("")
    sql_statements.append(
        "CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS list_search_indexes"
    )
    sql_statements.append("AS 'agpersist_search.list_search_indexes' LANGUAGE PYTHON;")
    sql_statements.append("")
    sql_statements.append("CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS list_indexes")
    sql_statements.append("AS 'agpersist_search.list_indexes' LANGUAGE PYTHON;")
    sql_statements.append("")

    # Register all registry mode UDTFs
    sql_statements.append("-- Registry Mode UDTFs (multi-field extraction)")
    for func_name, return_types in functions:
        sql_statements.append(
            f"CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS {func_name}"
        )
        sql_statements.append(f"AS 'agmap_registry.{func_name}' LANGUAGE PYTHON;")
        sql_statements.append("")

    return "\n".join(sql_statements)


def main():
    """Main entry point"""
    # Get the path to agmap_registry.py
    script_dir = Path(__file__).parent
    registry_file = script_dir.parent / "udfs" / "agmap_registry.py"

    # Extract function names
    functions = extract_udtf_names(registry_file)

    if not functions:
        print("No UDTFs found in agmap_registry.py", file=sys.stderr)
        sys.exit(1)

    # Generate SQL
    sql = generate_registration_sql(functions)

    # Print to stdout
    print(sql)

    # Also print summary to stderr
    print(f"\n-- Found {len(functions)} UDTFs:", file=sys.stderr)
    for func_name, _ in functions:
        print(f"--   - {func_name}", file=sys.stderr)


if __name__ == "__main__":
    main()

# Made with Bob
