
-- Found 7 UDTFs:
--   - agmap_productreview
--   - agmap_pr
--   - agmap_sentiment
--   - agmap_s
--   - agmap_test_generation
--   - agmap_electronics_reviews
--   - agmap_product_reviews
-- Auto-generated UDF Registration
-- Generated by auto_register_udfs.py
--
-- Total functions: 7

-- Dynamic Mode UDF (single field extraction)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap
AS 'ag_operators.agmap' LANGUAGE PYTHON;

-- AGReduce UDF (aggregation)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agreduce
AS 'agreduce.agreduce' LANGUAGE PYTHON;

-- AGSearch UDF (vector search)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agsearch
AS 'agsearch.agsearch' LANGUAGE PYTHON;

-- Explode Search Results UDTF
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS explode_search_results
AS 'agsearch.explode_search_results' LANGUAGE PYTHON;

-- AGPersist Search UDFs (persistent vector indexes)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS build_search_index
AS 'agpersist_search.build_search_index' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS search_index_json
AS 'agpersist_search.search_index_json' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS list_search_indexes
AS 'agpersist_search.list_search_indexes' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS list_indexes
AS 'agpersist_search.list_indexes' LANGUAGE PYTHON;

-- AGGenerate UDF (instance generation)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS aggenerate
AS 'aggenerate.aggenerate' LANGUAGE PYTHON;

-- Registry Mode UDTFs (multi-field extraction)
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_productreview
AS 'agmap_registry.agmap_productreview' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_pr
AS 'agmap_registry.agmap_pr' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_sentiment
AS 'agmap_registry.agmap_sentiment' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_s
AS 'agmap_registry.agmap_s' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_test_generation
AS 'agmap_registry.agmap_test_generation' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_electronics_reviews
AS 'agmap_registry.agmap_electronics_reviews' LANGUAGE PYTHON;

CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap_product_reviews
AS 'agmap_registry.agmap_product_reviews' LANGUAGE PYTHON;
