-- ============================================
-- AG Operators UDF Initialization for Flink SQL
-- ============================================
-- This file registers the unified agmap operator for semantic transformations
--
-- Usage in Flink SQL Client:
--   Copy and paste this entire file into the Flink SQL UI
--
-- ============================================

-- Set parallelism for better performance
SET 'parallelism.default' = '20';

-- Register the agmap UDTF for semantic transformations
CREATE TEMPORARY SYSTEM FUNCTION IF NOT EXISTS agmap
AS 'ag_operators.agmap' LANGUAGE PYTHON;

-- ============================================
-- Ready to Use!
-- ============================================
-- The agmap function is now registered and ready to use.
--
-- IMPORTANT: For maximum parallelism, use INSERT INTO instead of SELECT with LIMIT
-- SELECT queries with LIMIT force parallelism to 1 for the Python UDF operator
--
-- ============================================
-- USAGE EXAMPLES
-- ============================================
--
-- DYNAMIC MODE (No Schema Registry - Simplest)
-- ---------------------------------------------
-- Extract a single field on-the-fly without pre-registering schemas
--
-- 1. Extract sentiment from reviews (default string type):
--    SELECT T.sentiment
--    FROM pr, LATERAL TABLE(agmap(customer_review, 'sentiment')) AS T(sentiment);
--
-- 2. Extract rating as float:
--    SELECT T.rating
--    FROM pr, LATERAL TABLE(agmap(customer_review, 'rating', 'float')) AS T(rating);
--
-- 3. Extract emotion with description:
--    SELECT T.emotion
--    FROM pr, LATERAL TABLE(agmap(customer_review, 'emotion', 'str',
--                           'Primary emotion: joy, anger, sadness, fear, neutral')) AS T(emotion);
--
-- 4. Extract boolean field:
--    SELECT T.is_positive
--    FROM pr, LATERAL TABLE(agmap(customer_review, 'is_positive', 'bool')) AS T(is_positive);
--
-- REGISTRY MODE (Pre-registered Schemas)
-- ---------------------------------------------
-- Use schemas registered in Schema Registry for complex multi-field types
-- Set field_type to 'registry' to use Schema Registry
--
-- 5. Extract multiple fields from registered Sentiment schema:
--    SELECT T.sentiment_label, T.sentiment_score
--    FROM pr, LATERAL TABLE(agmap(customer_review, 'Sentiment', 'registry')) AS T(sentiment_label, sentiment_score);
--
-- Note: Registry mode requires the schema to be pre-registered in Schema Registry
--
-- ============================================
-- PARAMETER REFERENCE
-- ============================================
--
-- agmap(input_data, column_name, field_type, description)
--
-- Parameters:
--   1. input_data (required): The input data to process
--   2. column_name (required):
--      - Dynamic mode: Name of the field to extract
--      - Registry mode: Name of the registered schema
--   3. field_type (optional, default 'str'): Type specification
--      - 'str' or 'string': String type (dynamic mode)
--      - 'int' or 'integer': Integer type (dynamic mode)
--      - 'float' or 'double': Float type (dynamic mode)
--      - 'bool' or 'boolean': Boolean type (dynamic mode)
--      - 'registry': Use Schema Registry (registry mode)
--   4. description (optional, default None): Description to guide LLM (dynamic mode only, ignored in registry mode)
--
-- ============================================

-- Made with Bob
